### ISSUE TITLE
X-UMX - Separating using --context cpu takes very long

### ISSUE THREAD

**Issue by JeffreyCA** [sony/ai-research-code#2]
Thank you so much for open-sourcing X-UMX!

Is it in a usable state right now?

I followed your instructions to perform source separation with the model as listed [here](https://github.com/sony/ai-research-code/tree/feature/20201211-x-umx-nnabla/x-umx#source-separation-with-pretrained-model).

I ran `test.py` with the flag `--context cpu` and separation is taking a very long time, it took over 15 minutes for separating a 3-minute track. I have 16 GB of RAM. Is CPU-based separation supposed to take this long?

**Update:** It ended up exhausting all my memory and crashed.

**Comment by JeffreyCA** [comment]
As per [this tweet](https://twitter.com/tnarihi/status/1347346423377842176) CPU inference is not working right now.

> Seems like inference in CPU is not working properly now. We'll fix it right away. Sorry for the inconvenience.

**Comment by JeffreyCA** [comment]
Pulled the latest changes and it's working now, albeit a bit slowly.

**Comment by TakuyaNarihira** [comment]
Thanks for raising the issue. Now it's resolved in #6. Still it may be slow in CPU. Do you have a particular target CPU device you are restricted to use?

**Comment by JeffreyCA** [comment]
> Thanks for raising the issue. Now it's resolved in #6. Still it may be slow in CPU. Do you have a particular target CPU device you are restricted to use?

Could you clarify what you mean by that question? My CPU is an I7-9750H if that's what you are asking.
