### ISSUE TITLE
additional conda env dependencies needed

### ISSUE THREAD

**Issue by dts350z** [sony/ai-research-code#22]
to get this working I had to make the following changes to environment-gpu.yml

name: open-unmix-nnabla-gpu

channels:
  - conda-forge

dependencies:
  **- pip**
  - python=3.6
  - numpy=1.16
  - scikit-learn=0.21
  - tqdm=4.28
  - cudatoolkit=10.0
  - cudnn
  - ffmpeg
  - pip:
    **- soundfile**
    - musdb
    - norbert
    - resampy
    - nnabla
    - nnabla-ext-cuda100
    - pydub

**Comment by TomonobuTsujikawa** [comment]
Thank you for pointing out the missing components.
We will improve soon.
