### ISSUE TITLE
No pretrained models

### ISSUE THREAD

**Issue by BitBlueDevStudio** [sony/ai-research-code#31]
Hello!
I see now all links for pretrained models are 404, where can I get these models?

**Comment by TomonobuTsujikawa** [comment]
We're sorry, we missed some pretrained models.
Now, I uploaded missing pretrained models, please check it again!

You can download pretrained models for:
https://github.com/sony/ai-research-code/tree/master/x-umx
https://github.com/sony/ai-research-code/tree/master/d3net/semantic-segmentation
https://github.com/sony/ai-research-code/tree/master/d3net/music-source-separation

**Comment by BitBlueDevStudio** [comment]
Hello! Thanks very much! :) 
Also would be great if https://nnabla.org/pretrained-models/ai-research-code/d3net/mss/d3net-openvino.zip might be uploaded too

**Comment by TomonobuTsujikawa** [comment]
Yes, you're right completely...!
Now, you can download d3net-openvino.zip.

Sorry for inconvenience.

**Comment by BitBlueDevStudio** [comment]
Thanks :)

**Comment by prateekmalhotra** [comment]
Can we also have the pre-trained model for NVC Net? Thank you!
