### ISSUE TITLE
D3Net Music Source Separation pretrained model not downloadable

### ISSUE THREAD

**Issue by voodoohop** [sony/ai-research-code#36]
The link to the pretrained weights seems to be dead: https://nnabla.org/pretrained-models/ai-research-code/d3net/mss/d3net-mss.zip

**Comment by JeffreyCA** [comment]
The URL should be https://nnabla.org/pretrained-models/ai-research-code/d3net/mss/d3net-mss.h5.

**Comment by TomonobuTsujikawa** [comment]
Let me close due to already resolved.
