### ISSUE TITLE
test wavfile using cpu gives Segmentation fault

### ISSUE THREAD

**Issue by dharmesh8b** [sony/ai-research-code#4]
Hi,

I am using a pre-train model in a CPU environment with --context cpu option. my mixed wave file is 2 min long and I have a 16GB ram and an octa-core cpu system.

I am trying to run the test command for the pre-trained model and it gives segmentation fault. please check the below command and logs.
command: python test.py --input inputs/dm_mixed_vocal_and music_0002.wav --context cpu --model model/x-umx.h5 --outdir outputs/
logs:
2021-01-08 02:02:41,221 [nnabla][INFO]: Initializing CPU extension...
Segmentation fault (core dumped)

why this shows segmentation fault I don't know? Also, my system ram is not full at the time of segfault.
please suggest some ideas to resolve this issue.

**Comment by JeffreyCA** [comment]
As per [this tweet](https://twitter.com/tnarihi/status/1347346423377842176) CPU inference is not working right now.

> Seems like inference in CPU is not working properly now. We'll fix it right away. Sorry for the inconvenience.

**Comment by TakuyaNarihira** [comment]
#6 resolved the issue. Please try it. Thanks for the issue reporting.
