### ISSUE TITLE
Large delay during inference

### ISSUE THREAD

**Issue by philtsmith570** [sony/ai-research-code#42]
I'm running the nvcnet model after training and during inference there is a large time delay. The first inference is always large being around 3 seconds. All others have delays of about 1.2 seconds. The length of the wav file input doesn't change the delay.

After looking deeper it appears the delay is caused by the model construction. Is there a way to create the model object once and just do inference?

The delay makes the numbers posted in the paper to be false as you won't get the fast inference times that are published in the paper with these delays.

Any thoughts? I am still in the process of learning nnabla so maybe I am missing something about the library.

Best regards,
Philip

**Comment by TE-BacNguyenCong** [comment]
> After looking deeper it appears the delay is caused by the model construction. Is there a way to create the model object once and just do inference?

Yes, you can have the model construction once and do many inferences as follows.

```python
x = nn.Variable((1, 1, wave_length_x))
y = nn.Variable((1, 1, wave_length_y))
out = model(x, y) # setup time is measured here

# assuming that data contain a list of (x_audio, y_audio)
for x_audio, y_audio in data:
    # feed data to Variables
    x.d, y.d = x_audio, y_audio
    
    # call the forward
    out.forward(clear_buffer=True) # inference time should be measured only here
    
    # save output
    sf.write(args.output, out.d[0, 0], samplerate=hp.sr)
```

**Comment by philtsmith570** [comment]
Thank you for the input.  I think this is basically what I have been doing
to get around the model construction.  In essence the model becomes a
static model.

What I ran into is the wave_length_x & _y have to be a specific static size
before the model construction:

For example,

x = nn.Variable((1, 1, 32768))y = nn.Variable((1, 1, 32768))out =
model(x, y) # setup time is measured here

So input is set at 32768 time steps.  But, since the wav input may
vary the input must be broken down into chunks of 32768.  The
inference
must then perform on each step size of 32768 and then reconstructed
the by appending.  The inference for the model construction is
reduced but now many inferences must be performed.

For example,

x_audio = np.array([x_audio[x:x+32768] for x in range(0, len(x_audio),
32768)], dtype=object)

for wav in x_audio:
    if len(wav) == 32768:
        x_static.d = np.array(wav)
    else:
        wav = np.pad(wav, (0, 32768 - len(wav)), mode='constant')
    x_static.d = np.array(wav)
    out.forward(clear_buffer=True)
    audio_cmb = np.append(audio_cmb, out.d[0,0])

Is this what you are saying in your above code?  The inputs need to be a
defined size?

Thanks very much for your response,
Philip

**Comment by TE-BacNguyenCong** [comment]
Right, you need a fixed size for the inputs because this is a static model.

**Comment by philtsmith570** [comment]
Thanks!

I'm on the right track.

FYI - I do enjoy the nnabla library.  It is very engineering focused as
presented in paper.

Bests,
philip
