### ISSUE TITLE
Chinese supported?

### ISSUE THREAD

**Issue by KevinBaylor** [sony/ai-research-code#43]
Thank you for opensourcing the code. I'd like to know is mandarin Chinese supported in this project?

**Comment by TE-BacNguyenCong** [comment]
Although we haven't tested on any mandarin Chinese datasets, it should be possible because only speech waveforms are required for our method.

**Comment by TomonobuTsujikawa** [comment]
I think there seems to be no additional questions, please let me close this issue.
