### ISSUE TITLE
outputs not saved

### ISSUE THREAD

**Issue by dezorkic** [sony/ai-research-code#5]
the output wav files are not saved on disk anywhere, i tried multiple combinations, without the output argument, with the output argument, etc, none seem to work.

**Comment by TomonobuTsujikawa** [comment]
Hi,
If you use Google Colab and input minutes wav file, you may not be able to playback in Colab.
Even in such case, you can download the unmixed wav files locally with the following code.
```
from google.colab import files
files.download('./results/vocals.wav')
```

If you use Linux, I think you can find unmixed wav files in results directory.
```
$ python3 test.py --inputs over_minutes.wav --chunk-dur 10 --outdir ./results/
$ ls results
bass.wav  drums.wav  other.wav  vocals.wav
```

**Comment by dezorkic** [comment]
The code outputs only locally on Linux? I tried on Windows. Didn't know there was a difference if they both run on Python. I will check it out. Thanks!

**Comment by TomonobuTsujikawa** [comment]
Just for information, I tried on Windows conda environment.
In addition to basic nnabla (and ext-cuda) v1.15.0 environment, I installed/downloaded the followings:
* pip install norbert (0.2.1 is installed)
* pip install resampy (0.2.2 is installed)
* pip install soundfile (0.10.3.post1 is installed)
* pip install pydub (0.24.1 is installed)
* conda install ffmpeg (4.2.2 is installed)
* download pre-trained model from [here](https://nnabla.org/pretrained-models/ai-research-code/x-umx/x-umx.h5)
* prepare small wave file for test (I tried about 3 sec)

And run,

`(base) ...\ai-research-code-master\x-umx> python test.py --inputs input.wav --model x-umx.h5 --outdir ./results/
`

This creates 4 wav files in results directory.

**Comment by dezorkic** [comment]
I am going to wait for a PyTorch version if you guys do one, because I have lot of problems with NNabla with my current configuration.
