### ISSUE TITLE
NVCnet g_loss_con=0.0000 while training 

### ISSUE THREAD

**Issue by john852517791** [sony/ai-research-code#63]
i met two problems
first one is the same as the issue"https://github.com/sony/ai-research-code/issues/54" mentioned before
i tried to use docker environment that suggested in that issue
`docker pull nnabla/nnabla-ext-cuda-multi-gpu:py37-cuda110-mpi3.1.6-v1.29.0
docker run --rm -it -u $(id -u):$(id -g) --gpus all nnabla/nnabla-ext-cuda-multi-gpu:py37-cuda110-mpi3.1.6-v1.29.0

mpirun -n 2 python3 -c "import nnabla_ext.cudnn; from nnabla.ext_utils import get_extension_context; import nnabla.communicators as C; ctx = get_extension_context('cudnn', device_id='0'); C.MultiProcessDataParallelCommunicator(ctx)"`
and it went well
![image](https://user-images.githubusercontent.com/63532787/201576169-9c27d8c4-b17e-438d-92bd-19843e2b984e.png)
but then i tried to run the main.py and set the batchsize=8
and the error like this
`wzy@2f0a2b4b4485:~/NVCnet$ mpirun -n 1 python main.py  -c cudnn -d 7 --output_path log/baseline-wzy/ --batch_size 8
2022-11-14 04:17:10,938 [nnabla][INFO]: Initializing CPU extension...
2022-11-14 04:17:11,300 [nnabla][INFO]: Initializing CUDA extension...
2022-11-14 04:17:20,009 [nnabla][INFO]: Initializing cuDNN extension...
2022-11-14 04:17:20,359 [nnabla][INFO]: Training data with 103 speakers.
2022-11-14 04:17:20,360 [nnabla][INFO]: DataSource with shuffle(True)
2022-11-14 04:17:20,371 [nnabla][INFO]: Using DataIterator
Running epoch=1 lr=0.00010
[   0/4689]     d_loss 4.1589 (4.1589)  g_loss_avd 2.0793 (2.0793)      g_loss_con 0.0000 (0.0000)      g_loss_rec 58.3829 (58.3829)    g_loss_kld 0.0000 (0.0000)
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate again.
Error during backward propagation:
  Add2CudaCudnn
  Add2CudaCudnn
  Add2CudaCudnn
  MulScalarCuda
  MeanCudaCudnn
  SquaredErrorCuda
  Div2Cuda
  PowScalarCuda
  SumCuda
  AddScalarCuda
  PowScalarCuda
  ConvolutionCudaCudnn
  PadCuda
  GELUCuda
  ConvolutionCudaCudnn
  PadCuda
  GELUCuda
  ConvolutionCudaCudnn
  GELUCuda
  Add2CudaCudnn
  ConvolutionCudaCudnn
  Mul2Cuda
  TanhCudaCudnn
  SigmoidCudaCudnn
  SliceCuda <-- ERROR
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    run(args)
  File "main.py", line 70, in run
    Trainer(gen, gen_optim, dis, dis_optim, dataloader, rng, hp).run()
  File "/home/wzy/NVCnet/train.py", line 156, in run
    self.train_on_batch(i)
  File "/home/wzy/NVCnet/train.py", line 196, in train_on_batch
    p['g_loss'].backward(clear_buffer=True)
  File "_variable.pyx", line 827, in nnabla._variable.Variable.backward
RuntimeError: memory error in alloc
/home/gitlab-runner/builds/LRsSYq-B/0/nnabla/builders/all/nnabla/src/nbla/memory/memory.cpp:39
Failed `this->alloc_impl()`: N4nbla10CudaMemoryE allocation failed.

--------------------------------------------------------------------------`

when i changed the batchsize to 7 or 6 or 2，the glosscon is 0 all the time
![image](https://user-images.githubusercontent.com/63532787/201576564-598643bb-28ed-4925-8acf-1528aa815e07.png)

this is the result of nvidia-msi
![image](https://user-images.githubusercontent.com/63532787/201576897-334cd66a-b084-45ae-af6d-4384f1a31860.png)

plz,enlighten me

**Comment by yt605155624** [comment]
@john852517791 have you trained this model? does it reproduce the result of demo page?
