### ISSUE TITLE
Value error in nnabla on running x-umx on Rpi4, Raspberry Pi OS

### ISSUE THREAD

**Issue by RajivX** [sony/ai-research-code#7]
On running x-umx on Rpi4, 8GB on Raspberry Pi OS i get the below error,

root@raspberrypi:/home/pi/x-umx# python3 test.py --inputs ../Music/test_16k_S16_LE_stereo.wav --context cpu --model /home/pi/x-umx/x-umx.h5 --outdir /home/pi/x-umx/results
2021-01-30 16:37:37,007 [nnabla][INFO]: Initializing CPU extension...
Traceback (most recent call last):
File "test.py", line 198, in
test()
File "test.py", line 170, in test
residual_model=args.residual_model
File "test.py", line 84, in separate
mix_spec, msk, _ = unmix_target(audio_nn, test=True)
File "/home/pi/x-umx/model.py", line 300, in call
lstm_out_bass = self.lstm(cross_1, nb_samples, "lstm_bass", test)
File "/home/pi/x-umx/model.py", line 231, in lstm
bidirectional=not self.unidirectional, training=not test, dropout=0.4, name=scope_name)
File "", line 8, in lstm
File "/usr/local/lib/python3.7/dist-packages/nnabla/parametric_functions.py", line 1567, in lstm
return F.lstm(x, h, c, weight_l0=w0, weight=w, bias=b, num_layers=num_layers, dropout=dropout, bidirectional=bidirectional, training=training)
File "", line 3, in lstm
File "/usr/local/lib/python3.7/dist-packages/nnabla/function_bases.py", line 222, in lstm
return F.LSTM(ctx, num_layers, dropout, bidirectional, training)(*inputs, n_outputs=n_outputs, auto_forward=get_auto_forward(), outputs=outputs)
File "function.pyx", line 292, in nnabla.function.Function.call
File "function.pyx", line 271, in nnabla.function.Function._cg_call
RuntimeError: value error in setup_impl
/home/pi/x-umx/nnabla/src/nbla/function/./generic/split.cpp:36
Failed num_outputs_ == outputs.size(): inputs[0].shape[axis] must be the same number as the outputs. inputs[0].shape[axis]: 431, outputs: 2.

I have successfully manually built & installed nnabla & llvmlite.
The latter was really very difficult to build & install.
root@raspberrypi:/home/pi/x-umx# pip3 freeze | grep 'nnabla'
nnabla==1.9.0

I think, now it is throwing error related to nnabla, of the input parameter size not equivalent to
output parameter size. Can you please suggest, where we need to set this nnabla files ?

Please help me.
Regards,
Rajiv.

**Comment by RajivX** [comment]
Yes, i could solve it successfully. I installed the latest version of nnabla, ver 1.17 as of today,
root@raspberrypi:/home/pi/x-umx/results# pip3 freeze | grep 'nnabla'
nnabla==1.17.0.dev1 

I ported x-umx successfully on my Rpi4, 8 GB. Yay...!!
This is the first succesful porting & running of x-umx on Rpi4.
I have run x-umx on a speech capture recorded with a MIC.
The speech capture is 16kHz, Stereo, S16_LE format wav.

After running this,
root@raspberrypi:/home/pi/x-umx# python3 test.py  --inputs ../Music/test_16k_S16_LE_stereo.wav --context cpu --model /home/pi/x-umx/x-umx.h5 --outdir /home/pi/x-umx/results

2021-01-31 08:16:34,465 [nnabla][INFO]: Initializing CPU extension...

Four outputs are generated inside 'results' folder(you can keep any other folder path as you pass in --outdir):

root@raspberrypi:/home/pi/x-umx/results# ls
bass.wav  drums.wav  other.wav	vocals.wav
 
I played each of them. It there was a 1 kHz background noise, which was there in the recording capture.
It has been eliminated at some places of the track & minimized throughout the track.
SO, yes, x-umx can be used as Speech Noise removal.

Spectrogram analysis to be done further for better analysis further. I will be attaching my output & input 
for everyone here. 

Thanks a lot, x-umx team from SONY.

Regards,
Rajiv.

**Comment by RajivX** [comment]
Attaching the INPUT recording capture done on Rpi4 using DMIC Soundcard(4-MIC KIT, AC108 ADC),[test_16k_S16_LE_stereo.wav],

And the OUTPUTS generated on Rpi4, 8GB after running x-umx,[bass.wav, drums.wav, other.wav, vocals.wav]
Please download the attached zip, [results_and_input.tar.bz2].



Please analyze.
Regards,
Rajiv.

**Comment by RajivX** [comment]
Please close the issue, as i have successfully resolved it.

Rajiv.

**Comment by TomonobuTsujikawa** [comment]
Thank you for running x-umx on Rpi4 environment!
We would like to support Rasberrry Pi environment in the near future!
