### ISSUE TITLE
This giving the following errors below

### ISSUE THREAD

**Issue by viny33** [sony/ai-research-code#8]
C:\Users\Vinicius111\Downloads\xumx-master\xumx-master\xumx>python test.py --input inputs/"C:\Users\Vinicius111\Music\Test.mp3"python test.py ----model model/C:\Users\Vinicius111\Downloads\x-umx.h5 --outdir outputs/
2021-01-30 12:04:32,295 [nnabla][INFO]: Initializing CPU extension...
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    from .args import get_inference_args
ModuleNotFoundError: No module named '__main__.args'; '__main__' is not a package

**Comment by TomonobuTsujikawa** [comment]
Thank you for reporting.
In my environment, I cannot reproduce your issue, so maybe I'm wrong,
Are there unnecessary dots? my code is:
`from args import get_inference_args`
but your error message reports:
`from .args import get_inference_args`

**Comment by TomonobuTsujikawa** [comment]
I hope this helps you.
I close this github issue. If you have additional question, please submit new one.
